# Build numbering format
name: $(BuildID)

trigger:
  - master
  - feat/*

pool:
  vmImage: "ubuntu-latest"


# Schedule
# ---------

schedules:
  - cron: "0 0 * * Mon"
    displayName: Weekly midnight build
    always: true
    branches:
      include:
        - master
        - releases/*


# Shared Templates
# ----------------

resources:
  repositories:
    - repository: templates
      type: github
      name: julie-ng/newtonjs-azure-templates
      endpoint: julie-ng # service connection


# Variables
# ---------

variables:
  # all variables prefixed `newton-` come from library
  - group: newton-common-vars

  # this pipeline:
  - name: image-namespace
    value: demo

  - name: image-name
    value: data-editor

  - name: docker-image
    value: $(newton-registry)/$(newton-demo-namespace)/$(image-name)

  - name: snapshot-tag
    value: $(docker-image):$(Build.BuildId)

  - name: dev-tag
    value: $(docker-image):dev

# Stages
# ------

stages:

  # Tests
  - stage: Tests
    displayName: "Test (Node.js)"
    jobs:
      - job: Audit
        steps:
          - script: npm audit
            displayName: Audit Dependencies
            continueOnError: true

      - job: Linter
        steps:
          - script: npm ci && npm run lint
            displayName: Lint Code

  # Docker: Build and Push
  - stage: BuildAndDeploy
    displayName: "Build and Deploy"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: build_and_deploy
        displayName: Build Docker and Push
        steps:
          - template: devops/steps-set-build-sha.yml@templates # sets `$(build-sha)`
          - template: devops/steps-docker-build-push.yml@templates
            parameters:
              devTag: $(dev-tag)
              snapshotTag: $(snapshot-tag)-$(build-sha)
          - template: devops/steps-deploy-app-service.yml@templates
            parameters:
              appName: $(pipeline-app-name)
              dockerImage: $(snapshot-tag)-$(build-sha)
              condition: always()